apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: platform-apps
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: my-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: platform-events
          patternType: literal
        operations: [Read, Write]
      - resource:
          type: group
          name: platform-
          patternType: prefix
        operations: [Read]