# Optimized Pipeline using Parallel Modular Actions
name: Pipeline

on:
  push:
    branches:
      - main
      - feature/pytest
      - feature/frontend

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: "internal-platform-api"
  REGION: "europe-west1"
  ARTIFACT_REPO_ID: "internal-platform-api"
  GCP_WIF_PROVIDER: "projects/1062901461072/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
  GCP_SERVICE_ACCOUNT: "github-actions-deploy@internal-platform-api.iam.gserviceaccount.com"

jobs:
  test:
    uses: null-pointer-sch/cicd-templates/.github/workflows/python-ci.yml@main
    with:
      python-version: "3.12"
      working-directory: "backend"

  build-and-publish:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/pytest' || github.ref == 'refs/heads/feature/frontend')
    strategy:
      matrix:
        include:
          - name: backend
            context: backend
            dockerfile: backend/Dockerfile
          - name: frontend
            context: frontend
            dockerfile: frontend/Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Inherited Auth from top-level env
      - name: Auth to GCP
        uses: null-pointer-sch/cicd-templates/actions/gcp-auth@main
        with:
          wif-provider: ${{ env.GCP_WIF_PROVIDER }}
          service-account: ${{ env.GCP_SERVICE_ACCOUNT }}
          region: ${{ env.REGION }}

      # Decoupled Build and Publish
      - name: Build ${{ matrix.name }}
        uses: null-pointer-sch/cicd-templates/actions/docker-build@main
        with:
          image-name: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO_ID }}/internal-platform-api-${{ matrix.name }}:${{ github.sha }}"
          dockerfile-path: ${{ matrix.dockerfile }}
          docker-context: ${{ matrix.context }}

      - name: Publish ${{ matrix.name }}
        uses: null-pointer-sch/cicd-templates/actions/docker-push@main
        with:
          image-name: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO_ID }}/internal-platform-api-${{ matrix.name }}:${{ github.sha }}"

  deploy-image:
    needs: build-and-publish
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/pytest' || github.ref == 'refs/heads/feature/frontend')
    uses: null-pointer-sch/cicd-templates/.github/workflows/terraform-deploy.yml@v1.5.0
    with:
      project-id: "internal-platform-api"
      region: "europe-west1"
      artifact-repo-id: "internal-platform-api"
      image-tag: ${{ github.sha }}
      working-directory: "terraform"
    secrets:
      GCP_WIF_PROVIDER: "projects/1062901461072/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
      GCP_SERVICE_ACCOUNT: "github-actions-deploy@internal-platform-api.iam.gserviceaccount.com"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
